#!/usr/bin/env bash
# Copy the tracked dotfiles into $HOME (existing files are backed up first).
source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"

log "Dotfiles"

# Resolve the Windows user once, here, so .zshrc never has to spawn cmd.exe at
# shell start and the repo carries no machine-specific username.
if is_wsl; then
    if winuser="$(detect_win_user)"; then
        mkdir -p "$HOME/.config"
        backup "$HOME/.config/wsl-env.zsh"
        cat > "$HOME/.config/wsl-env.zsh" <<WSLENV
# Generated by get-started on $(date +%Y-%m-%d). Re-run: ./install.sh --only dotfiles
export WIN_USER="$winuser"
export WIN_HOME="/mnt/c/Users/$winuser"
WSLENV
        info "WIN_USER=$winuser, WIN_HOME=/mnt/c/Users/$winuser"
    else
        warn "could not determine the Windows user name."
        warn "Write ~/.config/wsl-env.zsh by hand, or the cube/cmonitor aliases stay unset:"
        warn "  export WIN_USER=\"<name>\"; export WIN_HOME=\"/mnt/c/Users/<name>\""
    fi
fi

for f in .zshrc .zshenv .gitconfig .gitignore_global; do
    backup "$HOME/$f"
    cp "$REPO_DIR/dotfiles/$f" "$HOME/$f"
    info "installed ~/$f"
done

mkdir -p "$HOME/.config/clangd"
backup "$HOME/.config/clangd/config.yaml"
cp "$REPO_DIR/dotfiles/.config/clangd/config.yaml" "$HOME/.config/clangd/config.yaml"
info "installed ~/.config/clangd/config.yaml"

warn "Backups of anything replaced are under ~/.get-started-backup/"
